export const Random_Movies = [
<<<<<<< HEAD
    'bloodshot',
    'aquaman',
    'iron man',
    'iron man 2',
    'iron man 3',
    'Captain America: The First Avenger',
    'captain marvel',
    'ant-man',
    'free guy',
    'Knives Out',
]
=======
'Iron Man',
'The Incredible Hulk',
'Iron Man 2',
'Thor',
'Captain America: The First Avenger',
'The Avengers',
'Iron Man 3',
'Thor: The Dark World',
'Captain America: The Winter Soldier',
'Guardians of the Galaxy',
'Avengers: Age of Ultron',
'Ant-Man',
'Captain America: Civil War',
'Doctor Strange',
'Guardians of the Galaxy Vol. 2',
'Spider-Man: Homecoming',
'Thor: Ragnarok',
'Black Panther',
'Avengers: Infinity War',
'Ant-Man and the Wasp',
'Captain Marvel',
'Avengers: Endgame',
'Spider-Man: Far From Home',
'Jurassic World',
'Furious 7',
'Minions',
'Jurassic Park',
'Despicable Me 2',
'The Secret Life of Pets',
'The Fate of the Furious',
'E.T. the Extra-Terrestrial',
'Fast & Furious 6',
'Sing',
'Fast Five',
'The Lost World: Jurassic Park',
'Mamma Mia!',
'Fifty Shades of Grey',
'King Kong',
'Ted',
'Despicable Me',
'Meet the Fockers',
'Bruce Almighty',
'Jaws',
'Lucy',
'The Bourne Ultimatum',
'Les Misérables',
'Warcraft',
'The Mummy Returns',
'The Mummy',
'Jason Bourne',
'The Mummy: Tomb of the Dragon Emperor',
'Snow White and the Huntsman',
'Back to the Future',
]
>>>>>>> c852695e47e9654bce0bc9ab3b9fe195523873b4
